version: '3.8'

services:
  facturador:
    build: .
    volumes:
      - ./certificado:/app/certificado
      - ./archivos:/app/archivos
      - ./logs:/app/logs
      - ./.env:/app/.env
    command: python Facturador_lioren.py
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  scrap:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    command: python supervisor.py
    restart: unless-stopped

  scrap-santander:
    build: .
    volumes:
      - ./certificado:/app/certificado
      - ./archivos:/app/archivos
      - ./.env:/app/.env
    command: python Scrap_santander.py
    restart: unless-stopped

  scrap-santander-cla:
    build: .
    volumes:
      - ./certificado:/app/certificado
      - ./archivos:/app/archivos
      - ./.env:/app/.env
    command: python Scrap_santander_cla.py
    restart: unless-stopped

  scrap-estado:
    build: .
    volumes:
      - ./certificado:/app/certificado
      - ./archivos:/app/archivos
      - ./.env:/app/.env
    command: python Scrap_estado.py
    restart: unless-stopped 